language: rust

services:
  - docker

rust:
  - stable
  - beta
  - nightly

env:
  - TARGET=x86_64-unknown-linux-musl
  - TARGET=x86_64-unknown-linux-gnu

os:
  - linux

before_script:
  - export PATH="${PATH}:${HOME}/.cargo/bin"
  - rustup target add ${TARGET}

script:
  - cargo build --target ${TARGET} --verbose
  - cargo build --target ${TARGET} --verbose --release

before_deploy:
  - mkdir -p target/executable
  - cp target/${TARGET}/debug/crawler target/executable/crawler-${TRAVIS_RUST_VERSION}-${TARGET}-debug
  - cp target/${TARGET}/release/crawler target/executable/crawler-${TRAVIS_RUST_VERSION}-${TARGET}

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: target/executable/*
  on:
    repo: crawlis/crawler
    tags: true
    condition: ${TRAVIS_RUST_VERSION}=stable
  cleanup: false

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
