language: rust

services:
  - docker

rust:
  - stable
  - beta
  - nightly

env:
  - TARGET=x86_64-unknown-linux-musl
  - TARGET=x86_64-unknown-linux-gnu

os:
  - linux

install:
  - ./.travis/install.sh

script:
  - ./.travis/build.sh

deploy:
  provider: releases
  script:
  api_key:
    secure: test
  file_glob: true
  file: target/executable/*
  cleanup: false
  overwrite: true
  name: "$TRAVIS_TAG"
  #  body: "$JOURNAL"
  on:
    repo: crawlis/crawler
    tags: true

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
