[package]
name = "crawler"
version = "0.1.0"
authors = ["donacrio <donatien.criaud@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
tokio = { version = "0.2.20", features = ["full"] }
reqwest = { version = "0.10.4", features = ["json"] }
select = "0.4.3"