version: "3.7"
services:
  crawler:
    build:
      context: .
      dockerfile: ./dockerfiles/local-module-debug.Dockerfile
    env_file: .env
    environment:
      - NATS_URI=nats://nats:4222
    depends_on:
      - nats

  nats:
    image: "nats"
    expose:
      - "4222"
    ports:
      - "8222:8222"

  keeper:
    build:
      context: .
      dockerfile: ./dockerfiles/generic-module-debug.Dockerfile
      args:
        - MODULE_NAME=keeper
        - MODULE_TAG=v0.1.0
        - MODULE_TARGET=x86_64-unknown-linux-musl
    environment:
      - SERVER_PORT=3030
      - DATABASE_URL=postgresql://postgres:password@postgres-db/keeper

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keeper
    ports:
      - "5432:5432"
    restart: unless-stopped
